### ISSUE TITLE
Failed to acquire token silently. Call method AcquireToken

### ISSUE THREAD

**Issue by gest01** [AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet#3]
Hi,

Got some problems using your application.  I've configured my Azure B2C AD through the web.config files and when i click "Sign in" i see my identity provider. Login works so far (i see my username on the top right corner) and i'm able to execute the "To-Do List"-Action.  

But a soon as i stop the debugger and restart the Application by pressing F5, i get an error when i click on "To-Do List"-Action again.

**Failed to acquire token silently. Call method AcquireToken** -> [Code](https://github.com/AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet/blob/7c6221ba04c12da8c2c84187ec695b744cf3cc99/TaskWebApp/Controllers/TasksController.cs#L76-L76)

This happens, cause the user is still authenticated, but the [NaiveSessionCache](https://github.com/AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet/blob/7c6221ba04c12da8c2c84187ec695b744cf3cc99/TaskWebApp/Utils/NaiveSessionCache.cs#L12-L12) is empty after the applications restart.
- What's the real world scenario retrieving the bearer token using AuthenticationContext-class
- Your solution uses the Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory package. Is [Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/2.24.304111323) still not supporting Azure B2C ?

thanks

**Comment by vijayaramb** [comment]
I am also getting this error.

here is my code snippet:
aadInstance = "https://login.microsoftonline.com/{0}{1}{2}"

code snippet:
//string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
string userObjectID = _sessionLogic.GetUserObjectIDFromAAD(_userDetails);

```
        string authority = String.Format(CultureInfo.InvariantCulture, Startup.aadInstance, Startup.tenant, string.Empty, string.Empty);
        ClientCredential credential = new ClientCredential(Startup.clientId, Startup.clientSecret);

        // We don't care which policy is used to access the TaskService, so let's use the most recent policy
        //string mostRecentPolicy = ClaimsPrincipal.Current.FindFirst(Startup.AcrClaimType).Value;

        // Here you ask for a token using the web app's clientId as the scope, since the web app and service share the same clientId.
        // AcquireTokenSilentAsync will return a token from the token cache, and throw an exception if it cannot do so.
        AuthenticationContext authContext = new AuthenticationContext(authority, new NaiveSessionCache(userObjectID));
        AuthenticationResult result = await authContext.AcquireTokenSilentAsync(Startup.clientId, credential, new UserIdentifier(userObjectID, UserIdentifierType.UniqueId));
```

i am not using the above code in mvc web application, where microsoft login page pop up for the user login. Instead i am using this code in web api (say signin api) where i will get the user credentials, impilictly call AAD and get back the token for the user. Thats why i trying to use 'AcquireTokenSilentAsync'. But this is not working.

**Comment by dstrockis** [comment]
Please look for an update to this sample next week
