### ISSUE TITLE
ASP.NET Core version 1.1

### ISSUE THREAD

**Issue by Waldulmer** [AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet#8]
Can you please update your sample App to the latest ASP.NET Core version 1.1

**Comment by tanwarsatya** [comment]
I believe the code doesn't work with Asp.net Core hence I don't see any example or details about the same. Code with Old libraries and framework is causing too much confusion.

**Comment by derisen** [comment]
Closing as this repo is being archived.
